apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chronograf
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - image: quay.io/influxdb/chronograf:latest
        imagePullPolicy: Always
        name: chronograf
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: chronograf
          mountPath: /var/lib/chronograf
      volumes:
      - name: chronograf
        gcePersistentDisk:
          pdName: chronograf
          fsType: ext4