apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudapi
    component: cloudapi
  name: cloudapi
spec:
  selector:
    app: cloudapi
    component: cloudapi
  ports:
   - port: 55503
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudapi
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cloudapi
        component: cloudapi
    spec:
      containers:
      - name: cloudapi
        image: eu.gcr.io/cellarstone-1488228226623/cloudapi:0.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 55503
      imagePullSecrets:
      - name: registry-key

