apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: cloudnginx
    servicePort: 80
---    
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cloudnginx
    component: cloudnginx
  name: cloudnginx
spec:
  selector:
    app: cloudnginx
    component: cloudnginx
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudnginx
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cloudnginx
        component: cloudnginx
    spec:
      containers:
      - name: cloudnginx
        image: eu.gcr.io/cellarstone-1488228226623/cloudnginx:0.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: "secrets"
          mountPath: "/etc/secrets"
          readOnly: true
      imagePullSecrets:
      - name: registry-key
      volumes:
      - name: "secrets"
        secret: 
          secretName: "ssl-proxy-secret"