apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kapacitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kapacitor
    spec:
      containers:
      - image: kapacitor:1.1.0
        imagePullPolicy: Always
        name: kapacitor
        env:
        - name: KAPACITOR_HOSTNAME
          value: kapacitor
        - name: KAPACITOR_INFLUXDB_0_URLS_0
          value: http://influxdb:8086
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: kapacitor
          mountPath: /var/lib/kapacitor
      volumes:
      - name: kapacitor
        gcePersistentDisk:
          pdName: kapacitor
          fsType: ext4